augmentation:
  color_jitter:
    brightness: 0.2
    contrast: 0.2
    hue: 0.1
    saturation: 0.2
  horizontal_flip: true
  normalization:
    mean:
    - 0.485
    - 0.456
    - 0.406
    std:
    - 0.229
    - 0.224
    - 0.225
  random_erasing:
    p: 0.3
    ratio:
    - 0.3
    - 3.3
    scale:
    - 0.02
    - 0.1
  resize:
  - 224
  - 224
  rotation: 20
  vertical_flip: true
data:
  batch_size: 16
  num_workers: 4
  path: data/raw/Switzerland
  train_split: 0.8
inference:
  temperature: 1.1917283535003662
  threshold: 0.401
  threshold_global: 0.3351149559020996
  thresholds_per_fold:
    fold_0: 0.006015102379024029
    fold_1: 0.6420585513114929
    fold_2: 0.3572711646556854
model:
  name: resnet18
  num_classes: 2
  pretrained: true
scheduler:
  factor: 0.5
  min_lr: 1e-6
  mode: min
  patience: 3
training:
  device: cpu
  dropout_prob: 0.3
  epochs: 20
  learning_rate: 1e-4
  mixup_alpha: 0.4
  mixup_prob: 0.5
  pct_start: 0.3
  scheduler: onecycle
  use_cutmix: false
  weight_decay: 5e-5
