data:
  path: 'data/raw/Switzerland'
  train_split: 0.8
  batch_size: 16
  num_workers: 4

model:
  name: 'resnet18'
  pretrained: true
  num_classes: 2

training:
  epochs: 20
  learning_rate: 1e-4
  weight_decay: 5e-5
  device: 'cpu'

scheduler:
  mode: 'min'
  factor: 0.5
  patience: 3
  min_lr: 1e-6

augmentation:
  resize: [224, 224]
  horizontal_flip: true
  vertical_flip: true
  rotation: 20
  color_jitter:
    brightness: 0.2
    contrast: 0.2
    saturation: 0.2
    hue: 0.1
  random_erasing:
    p: 0.3
    scale: [ 0.02, 0.1 ]
    ratio: [ 0.3,  3.3 ]
  normalization:
    mean: [0.485, 0.456, 0.406]
    std:  [0.229, 0.224, 0.225]