seed: 42

dataset:
  raw_dir: data/processed/all
  splits_dir: splits/all/finetune

model:
  name: resnet50
  pretrained: true
  num_classes: 1

input:
  size: [224, 224]
  batch_size: 32

augmentation:
  rotation_range: 30
  width_shift_range: 0.2
  height_shift_range: 0.2
  shear_range: 0.2
  zoom_range: 0.2
  horizontal_flip: true
  brightness_range: [0.8, 1.2]
  contrast_range: [0.8, 1.2]
  cutout_size: [20, 20]

training:
  epochs: 40
  optimizer:
    type: AdamW
    lr: 3e-4
    weight_decay: 1e-4
  scheduler:
    type: CosineAnnealingLR
    T_max: 40
  callbacks:
    early_stopping:
      monitor: val_pr_auc
      mode: max
      patience: 5
    model_checkpoint:
      monitor: val_recall_toxic
      mode: max
      save_best_only: true

loss:
  name: BCEWithLogitsLoss
  class_weights:
    non_toxic: 0.58
    toxic: 0.42

metrics:
  - accuracy
  - precision_toxic
  - recall_toxic
  - f1_macro
  - roc_auc
  - pr_auc

device: cuda
verbosity: 1
