seed: 42

augmentation:
  resize: [224, 224]
  rotation: 20
  color_jitter:
    brightness: 0.2
    contrast: 0.2
    saturation: 0.2
    hue: 0.1
  horizontal_flip: true
  vertical_flip: true
  rand_augment:
    num_ops: 2
    magnitude: 9
  random_erasing:
    p: 0.3
    scale: [0.02, 0.1]
    ratio: [0.3, 3.3]
  normalization:
    mean: [ 0.485, 0.456, 0.406 ]
    std: [ 0.229, 0.224, 0.225 ]

data:
  path: data/raw/Switzerland
  batch_size: 32
  num_workers: 2

model:
  architecture: efficientnet_b0
  pretrained: true
  num_classes: 2
  dropout_prob: 0.3

training:
  device: auto
  epochs: 30
  patience: 5
  learning_rate: 5e-5
  weight_decay: 5e-5
  mixup_alpha: 0.4
  use_cutmix: true
  label_smoothing: 0.1

scheduler:
  type: CosineAnnealingLR
  T_max: 30
  eta_min: 1e-6

validation:
  tolerance: 0.13

inference:
  thresholds:
    start: 0.1
    end: 0.9
    num: 17
  default_threshold: 0.5

threshold: 0.5
