augmentation:
  color_jitter:
    brightness: 0.2
    contrast: 0.2
    hue: 0.1
    saturation: 0.2
  horizontal_flip: true
  vertical_flip: true
  rotation: 20
  resize: [224, 224]
  normalization:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  random_erasing:
    p: 0.3
    scale: [0.02, 0.1]
    ratio: [0.3, 3.3]

data:
  path: data/raw/Switzerland
  batch_size: 16
  num_workers: 4

model:
  num_classes: 2
  pretrained: true
  architectures:
    - resnet18
    - efficientnet_b0
    - mobilenet_v3_small
    - vit_b_16

training:
  device: auto
  epochs: 20
  learning_rate: 1e-4
  weight_decay: 5e-5
  dropout_prob: 0.3
  mixup_alpha: 0.4
  mixup_prob: 0.5
  pct_start: 0.3
  use_cutmix: false

scheduler:
  factor: 0.5
  patience: 3
  min_lr: 1e-6
  mode: min

inference:
  threshold: 0.5
  temperature: 1.0
