data:
  path: 'data/raw/Switzerland'
  train_split: 0.8
  batch_size: 16
  num_workers: 4

model:
  name: 'resnet50'
  pretrained: true
  num_classes: 2

training:
  epochs: 20
  learning_rate: 1e-4
  weight_decay: 1e-5
  device: cpu

augmentation:
  resize: [224, 224]
  horizontal_flip: true
  rotation: 20
  normalization:
    mean: [0.485, 0.456, 0.406]
    std:  [0.229, 0.224, 0.225]
